from textual.app import App, ComposeResult
from textual.widgets import Label, Button
from textual import containers

BUTTON_STYLES = "width: auto; height: auto; border-top: none; border-bottom: none;"

class LayoutExample(App):
    def compose(self) -> ComposeResult:
        yield containers.Horizontal(
            containers.Vertical(
                Label("Menu"),
                containers.Vertical(
                    Button("One").set_styles(BUTTON_STYLES),
                    Button("Two").set_styles(BUTTON_STYLES),
                    Button("Three").set_styles(BUTTON_STYLES),
                    Button("Four").set_styles(BUTTON_STYLES),
                    Button("Five").set_styles(BUTTON_STYLES),
                    Button("Six").set_styles(BUTTON_STYLES),
                    Button("Seven").set_styles(BUTTON_STYLES),
                    Button("Eight").set_styles(BUTTON_STYLES),
                    Button("Nine").set_styles(BUTTON_STYLES),
                    Button("Ten").set_styles(BUTTON_STYLES),
                    Button("Eleven").set_styles(BUTTON_STYLES),
                    Button("Twelve").set_styles(BUTTON_STYLES),
                    Button("Thirteen").set_styles(BUTTON_STYLES),
                    Button("Fourteen").set_styles(BUTTON_STYLES),
                    Button("Fifteen").set_styles(BUTTON_STYLES),
                    Button("Sixteen").set_styles(BUTTON_STYLES),
                    Button("Seventeen").set_styles(BUTTON_STYLES),
                    Button("Eighteen").set_styles(BUTTON_STYLES),
                    Button("Nineteen").set_styles(BUTTON_STYLES),
                    Button("Twenty").set_styles(BUTTON_STYLES),
                    Button("TwentyOne").set_styles(BUTTON_STYLES),
                    Button("TwentyTwo").set_styles(BUTTON_STYLES),
                    Button("TwentyThree").set_styles(BUTTON_STYLES),
                    Button("TwentyFour").set_styles(BUTTON_STYLES),
                    Button("TwentyFive").set_styles(BUTTON_STYLES),
                    Button("TwentySix").set_styles(BUTTON_STYLES),
                    Button("TwentySeven").set_styles(BUTTON_STYLES),
                    Button("TwentyEight").set_styles(BUTTON_STYLES),
                    Button("TwentyNine").set_styles(BUTTON_STYLES),
                    Button("Thirty").set_styles(BUTTON_STYLES),
                    Button("ThirtyOne").set_styles(BUTTON_STYLES),
                    Button("ThirtyTwo").set_styles(BUTTON_STYLES),
                    Button("ThirtyThree").set_styles(BUTTON_STYLES),
                    Button("ThirtyFour").set_styles(BUTTON_STYLES),
                    Button("ThirtyFive").set_styles(BUTTON_STYLES),
                    Button("ThirtySix").set_styles(BUTTON_STYLES),
                    Button("ThirtySeven").set_styles(BUTTON_STYLES),
                    Button("ThirtyEight").set_styles(BUTTON_STYLES),
                    Button("ThirtyNine").set_styles(BUTTON_STYLES),
                    Button("Forty").set_styles(BUTTON_STYLES),
                ).set_styles("width: auto; overflow-y: auto;"),
            ).set_styles("width: auto;"),
            containers.Vertical(
                containers.Horizontal(
                    Button("AAAA").set_styles(BUTTON_STYLES),
                    Label("BBBB"),
                    Button("CCCC").set_styles(BUTTON_STYLES),
                ).set_styles("width: auto; height: auto;"),
                containers.Vertical(
                    Label("One"),
                    Label("Two"),
                    Label("Three"),
                    Label("Four"),
                    Label("Five"),
                    Label("Six"),
                    Label("Seven"),
                    Label("Eight"),
                    Label("Nine"),
                    Label("Ten"),
                    Label("Eleven"),
                    Label("Twelve"),
                    Label("Thirteen"),
                    Label("Fourteen"),
                    Label("Fifteen"),
                    Label("Sixteen"),
                    Label("Seventeen"),
                    Label("Eighteen"),
                    Label("Nineteen"),
                    Label("Twenty"),
                    Label("TwentyOne"),
                    Label("TwentyTwo"),
                    Label("TwentyThree"),
                    Label("TwentyFour"),
                    Label("TwentyFive"),
                    Label("TwentySix"),
                    Label("TwentySeven"),
                    Label("TwentyEight"),
                    Label("TwentyNine"),
                    Label("Thirty"),
                    Label("ThirtyOne"),
                    Label("ThirtyTwo"),
                    Label("ThirtyThree"),
                    Label("ThirtyFour"),
                    Label("ThirtyFive"),
                    Label("ThirtySix"),
                    Label("ThirtySeven"),
                    Label("ThirtyEight"),
                    Label("ThirtyNine"),
                    Label("Forty"),
                ).set_styles("width: 1fr; height: 1fr; overflow-y: auto;"),
            ).set_styles("width: 1fr;"),
        )

if __name__ == "__main__":
    app = LayoutExample()
    app.run()